sensors: ["lidar_pointcloud"]
lidar_pointcloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /left_lidar/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 0.8
    max_update_rate: 10.0
    filtered_cloud_topic: filtered_cloud